[package]
name = "maintain"
version = "0.1.0"
authors = ["Ross Todd <rosstodd@lululemon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1"
indicatif = "0.15.0"
